### ISSUE TITLE
Inconsistent results of action vs. applyPatches vs. applySnapshot

### ISSUE THREAD

**Issue by sisp** [xaviergonz/mobx-keystone#116]
I've noticed inconsistent results of an action (move element to the end of an array) vs. `applyPatches` vs. `applySnapshot` when using a (root) ref which removes the node when it cannot be resolved anymore - which is a pretty standard use case.

```ts
test("applySnapshot - applyPatches - ref", () => {
  const bRef = rootRef<B>("bRef", {
    onResolvedValueChange(_, next, prev) {
      if (prev && !next) {
        detach(prev)
      }
    },
  })

  @model("A")
  class A extends Model({ b: prop<Ref<B>>() }) {}

  @model("B")
  class B extends Model({}) {}

  @model("R")
  class R extends Model({ as: prop<A[]>(), bs: prop<B[]>() }) {
    @modelAction
    moveToEnd(index: number) {
      const a = this.as.splice(index, 1)[0]
      this.as.push(a)
    }
  }

  const b1 = new B({})
  const a1 = new A({ b: bRef(b1) })
  const b2 = new B({})
  const a2 = new A({ b: bRef(b2) })
  const ro = new R({ as: [a1, a2], bs: [b1, b2] })
  const rp = clone(ro, { generateNewIds: false })
  const rs = clone(ro, { generateNewIds: false })

  // record patches and take a snapshot
  const patches: Patch[][] = []
  autoDispose(
    onPatches(ro, p => {
      patches.push(p)
    })
  )
  ro.moveToEnd(0)
  const snapshot = getSnapshot(ro)

  expect(ro.as).toHaveLength(2)
  expect(ro.bs).toHaveLength(2) // is 2 :-)

  // apply patches
  runInAction(() => {
    for (let i = 0; i < patches.length; i++) {
      applyPatches(rp, patches[i])
    }
  })

  expect(rp.as).toHaveLength(2)
  expect(rp.bs).toHaveLength(2) // is 1 :-(

  // apply snapshot
  applySnapshot(rs, snapshot)
  expect(rs.as).toHaveLength(2)
  expect(rs.bs).toHaveLength(2) // is 0 :-(
})
```

**Comment by xaviergonz** [comment]
That's because:

- In the case of using "real objects" the ref object is actually being moved around (in other words, the same instance gets detached then attached again somewhere else). This means the referenced objects is unresolved (when the reference object is detached) and then found again (when the reference object is re-attached again), so no change is actually issued.

- In the case of patches the ref object gets destroyed/detached and then a new reference object of the same kind gets created/attached. This means for the original object the referenced object is no longer resolvable (so it calls detach) and for the new reference object it is the first time it was created (so it does not call on change at all)

- For snapshot the same as with patches happen, but this time with both references.

I created a PR (https://github.com/xaviergonz/mobx-keystone/pull/117) that improves the reconciliation algorithm so it will try to reuse the model objects whenever possible, which fixes this issue and should end up in a more similar behaviour.

**Comment by sisp** [comment]
The PR looks great, thank you very much!

**Comment by xaviergonz** [comment]
Out with v0.38.0

**Comment by sisp** [comment]
Thanks again, it appears solve the problems I've been having. :-)
