### ISSUE TITLE
(pre/post)ProcessSnapshot hooks to customize $modelID key (i.e. _id) for better interoperability with Databases. 

### ISSUE THREAD

**Issue by ckwong90** [xaviergonz/mobx-keystone#121]
I am considering migrating my mobx-state-tree models to mobx-keystone since it does solve many of the pain points when using with typescript.

However, one of the features mobx-state-tree has is to specify its own ID property ( via types.identifier) and I've been using "_id" as a the id key since NoSQL (such as MongoDB in my case) requires "_id" for its data.

With mobx-state-tree, its snapshot is already in its desired form. Perhaps a hook in the model like mst's preProcessSnapshot and postProcessSnapshot can be used to convert the keys.

From the MST docs:

preProcessSnapshot | Before creating an instance or applying a snapshot to an existing instance, this hook is called to give the option to transform the snapshot before it is applied. The hook should be a pure function that returns a new snapshot. This can be useful to do some data conversion, enrichment, property renames, etc. This hook is not called for individual property updates. **Note 1: Unlike the other hooks, this one is _not created as part of the actions initializer, but directly on the type!_ _Note 2: The preProcessSnapshot transformation must be pure; it should not modify its original input argument!**_
-- | --
postProcessSnapshot | This hook is called every time a new snapshot is being generated. Typically it is the inverse function of preProcessSnapshot. This function should be a pure function that returns a new snapshot. **Note: Unlike the other hooks, this one is _not created as part of the actions initializer, but directly on the type!**_

**Comment by xaviergonz** [comment]
Is the reason because of reference ids?

If so there are two solutions to this:
- you could use a custom reference that uses another id field (whichever you want) to resolve the reference
- you can create a getRefId() override method in the model that returns that other id field so "standard" reference implementations use that id instead

If the reason is to skip $modelId at all, then your own post at https://github.com/xaviergonz/mobx-keystone/issues/123#issuecomment-585481064 pretty much sums up why it would be a difficult change to do.

Another option would be to use a normal object instead to hold that data inside the "wrapper" model, which doesnt require modelId/modelType at all.

**Comment by faassen** [comment]
Note: I don't know much about mobx-keystone yet, but I'm investigating it as a possible alternative to mobx-state-tree, due to its nicer typescript support and more natural class-based models.

My use case involves a REST API that exposes resources that have an 'id' field, and references that use this id as well. If I understand it correctly you can use functional models, but that takes away the whole "just use classes" advantage of mobx-keystone.

To help me understand this topic better, I'm trying to understand why this modelId requirement exists. My understanding is to support 'fromSnapshot', as the inverse of 'getSnapshot'. The type identifier is needed to know which model class to use, but why the modelId?

**Comment by faassen** [comment]
Is it possible to construct modelId from other properties? 

Keep $modelId, but the backend may omit $modelId if the developer provides a way to construct it from other data in the snapshot, for instance from a combination of $modelType and an "id" field (that is unique per type but not globally unique).

**Comment by xaviergonz** [comment]
Sure, assuming your data does not have neither $modelType nor $modelId you can do this:
```ts
// using new Model
const myModel = new MyModel(
   $modelId: "whatever string id", // or do not pass anything to auto generate one
   ...backendData
})

// using fromSnapshot
const sn = modelSnapshotInWithMetadata(MyModel,
backendData,
"whatever string id"
const myModel = fromSnapshot<MyModel>(sn);
```

You might also want to check out functional models (https://mobx-keystone.netlify.app/functionalModels) which do not require either of those present.

Also consider that if the data coming from the backend does not contain actions to modify itself (is sort of immutable) probably all you want is a plain object stored inside a model property instead of a full fledged model instance.

**Comment by xaviergonz** [comment]
@ckwong90 Not sure if this feature helps this case, but it was just released:

0.50.0
It is now possible to use a custom property as model id instead of $modelId by assigning to a property the new idProp value. In any case, model instances can still use model.$modelId to read/write this custom property if desired.
Customizing the ID property
It is possible to use any other custom property as ID source by assigning to it the idProp value. For example:

@model("myApp/ModelWithCustomId")
class ModelWithCustomId extends Model({
  customId: idProp
}) {
  ...
}
In this case either customId (both in snapshots and instances) or $modelId (only in instances) can be used to read / write the ID property.

**Comment by xaviergonz** [comment]
Closing due to lack of feedback on the released features that should address this
