### ISSUE TITLE
Perspective and missing documentation

### ISSUE THREAD

**Issue by benediktdertinger** [xaviergonz/mobx-keystone#145]
Hi @xaviergonz,

thank you for all your efforts to create and maintain this library for better Typescript support. As we are developing huge SPAs we are currently thinking about switching from mobx-state-tree to mobx-keystone. To be able to make such a huge step we need some confidence to be sure this can become an long-term alternative. I know that this is a lot to ask but if you already have some plans it would be really great if you could share them with us so we can decide to do the switch and maybe even contribute to your alternative.

Currently I started a new test project and since yesterday the docs are not available anymore (which is quite complicated to handle): https://mobx-keystone.js.org/

And do you plan to improve the async/await API? Currently it seems to be a bit bumpy.

Please don't get me wrong: I know that you are putting a lot of effort in this – it's just that we need a perspective to make this step.

**Comment by xaviergonz** [comment]
Hello, first of all thanks for considering the library.

I'm not sure I follow, what do you mean by plans?

> Currently I started a new test project and since yesterday the docs are not available anymore (which is quite complicated to handle): https://mobx-keystone.js.org/

Should be fixed now, the docs failed to build after the last dev dependency updates.

> And do you plan to improve the async/await API? Currently it seems to be a bit bumpy.

Yeah, that's due to the lack of better typing support from TS for generator functions. If there were to be any improvements (unless TS guys suddenly improved such generator function typings) it would be something in the form of https://github.com/mobxjs/mobx-utils#actionasync

That being said, I usually find it is easier to have mutations in synchronous actions and a plain async method that calls these sync actions. For example:

```ts
@model(....)
class M extends Model({
  x: prop(0, { setterAction: true }),
  y: prop(0)
}) {
  @modelAction
  setY(y: number) { this.y = y }

  async something() {
    this.x = 10; // this is called/recorded as a sync action
    await delay(100)
    this.setY(20); // this is called/recorded as a sync action
  }
}
```

The only case were this would not be OK is if you were to do server/client action replication and you wanted the client to also have a delay as well (as it would happen in the server), or if you wanted to undo the async action as a single unit, but in any other case the pattern above should yield the same mutations.

**Comment by benediktdertinger** [comment]
Hi @xaviergonz,

thanks for your detailed feedback. We have been using your library a lot in the last two weeks. It took me a while to get used to it but most of the parts were related to MST patterns I was used to and I found your structure and syntax a lot more intuitive regarding TS patterns. 

I think we could help people onboarding by adding more details and examples. Are you interested in proposals?

Regarding my question: Do you plan to maintain this lib in a long-term perspective? And what about MST? I read that you are involved in both projects. Do you thing they will add better TS support and in the end it makes more sense to use the current MST lib and wait for updates or do you suggest switching to keystone is a safe thing regarding support and updates in the upcoming years?

Thank you as well for your update on async actions – I will used it tomorrow.

Again: Great job and thank you a lot!

**Comment by xaviergonz** [comment]
> I think we could help people onboarding by adding more details and examples. Are you interested in proposals?

Sure, any feedback/ideas are appreciated. :)

> Do you plan to maintain this lib in a long-term perspective? 

Yep.

> And what about MST? I read that you are involved in both projects. Do you thing they will add better TS support and in the end it makes more sense to use the current MST lib and wait for updates or do you suggest switching to keystone is a safe thing regarding support and updates in the upcoming years?

Although very similar, there are several key conceptual differences between both projects (e.g. $modelId, not making runtime type checking mandatory, no lazy initialization, etc.).

Also, (right now, AFAIK) MST is more of a community-based project than mobx-keystone at the moment, so decisions have to be agreed upon (for example the class/decorator based syntax was proposed but rejected in the end) and also due to its success it aims to have a more stable API. 

Those are actually part of what drove me to create mobx-keystone actually.

> Again: Great job and thank you a lot!

Thank you!
