### ISSUE TITLE
Using applySnapshot to restore from saved local snapshot

### ISSUE THREAD

**Issue by robclouth** [xaviergonz/mobx-keystone#147]
When the app opens I want to hydrate the locally stored state like this:
```applySnapshot(this, storeJson);```
However it's complaining that the ids have changed. Can I applySnapshots while ignoring the ids? Creating new ones etc?
I could do fromSnapshot but then I can't assign the result to ```this```. It's less convenient because I'd need to have a separate class to handle rehydrating.

**Comment by martinheidegger** [comment]
hello @robclouth, it would be good to post an error message.

Generally when applying a snapshot it should remove objects with id's not in the snapshop, add objects from the snapshot that are missing and modify objects if the id matches.

I could see that a problem may occur if the snapshot contains a reference to an object by an id but does not contain the object the id specified in the reference.

**Comment by xaviergonz** [comment]
Hello,
it is on purpose. applySnapshot direct target should be the same "instance" of an object (sub-objects can different though). 

While it is true that applySnapshot could be relaxed so it changes the id of the target object, why not just use `fromSnapshot` to re-hydrate like you said instead?

e.g.
```ts
const myNode = new MyNode({...})
applySnapshot(myNode, myNodeSnapshot)
// vs
const myNode = fromSnapshot<MyNode>(myNodeSnapshot)
```

It should be even easier since you don't need to initialize MyNode with dummy data.

If you still want to use applySnapshot for some reason one easy tweak would be to override the snapshot id with the current object id before applying it. 

```ts
const myNode = new MyNode({...})
applySnapshot(myNode, { $modelId: myNode.id, ...myNodeSnapshot })
```

or the other way around, create the node with the same id as the snapshot
```ts
const myNode = new MyNode({$modelId: myNodeSnapshot.$modelId, ...})
applySnapshot(myNode, myNodeSnapshot)
```

**Comment by robclouth** [comment]
Thanks! I'll do the second way. It's because I want to have a "load"
function within the class that gets the json from local storage and updates
the state of that instance. Otherwise I'd need to handle the loading from
outside the class.

**Comment by xaviergonz** [comment]
You could also use fromSnapshot from within a static method of the class

```ts
...
class MyNode ... {
  static load(): MyNode {
    ...
    return fromSnapshot<MyNode>(data); 
  }
}

const myNode = MyNode.load();
```

**Comment by robclouth** [comment]
Thanks, I've done the second method
