### ISSUE TITLE
Grouping patches in undoMiddleware

### ISSUE THREAD

**Issue by robclouth** [xaviergonz/mobx-keystone#150]
What's the best way of merging patches into a single undo object? Like the ```startGroup``` thing in MST. [Link](https://github.com/mobxjs/mobx-state-tree/blob/master/packages/mst-middlewares/README.md)

**Comment by robclouth** [comment]
Looking at MST source code they use one recorder per group. What's the easiest way I could implement this?

**Comment by robclouth** [comment]
Ok the way I did it was to modify the UndoStore to store the events in groups instead of individually. Then if isGroup is true the events get added to the group instead of undoQueue. Then when the group is finished the groupedEvents are added to the queue.
The group must be reversed upon undoing.

**Comment by xaviergonz** [comment]
Since right now undo is already grouped for actions you might want to consider just wrapping all "grouped" children actions inside a single parent model action / model flow if possible.

**Comment by airtonix** [comment]
@xaviergonz the caveat to this is deleting Nodes with references.

Currently if you have a Node that has even one reference, then you get the action to remove the node and another action for each reference.

We've just built a react application that builds forms for ReactJsonSchemaForm, we use references a lot. Our variation of RJSF has Pages, Sections and Fields.

Our scenario looks a bit like this:

```ts
@model('Form')
class FormModel extends model({
  id: prop<string>(() => FormUnitIdentityService('form')),
  fields: prop<AnyFieldModel[]>(() => []),
  sections: prop<SectionModel[]>(() => []),
  pages: prop<PageModel[]>(() => []),
}) {
  @modelAction
  removeField(fieldNodeToRemove: AnyFieldModel): void {
    const fieldIndex = this.fields.findIndex((field) => field.id === fieldNodeToRemove.id)
    this.fields = this.fields.splice(fieldIndex, 1)
  }
}

@model('Page')
class PageModel extends model({
  id: prop<string>(() => FormUnitIdentityService('page')),
  sections: prop<Ref<SectionModel>[]>(() => []),
  fields: prop<Ref<AnyFieldModel>[]>(() => []),
}) {}

@model('Section')
class SectionModel extends model({
  id: prop<string>(() => FormUnitIdentityService('section')),
  fields: prop<Ref<AnyFieldModel>[]>(() => []),
  rows: prop<SectionRowModel[]>(() => [])
}) {}

@model('SectionRow')
class SectionRowModel extends model({
  id: prop<string>(() => FormUnitIdentityService('sectionrow')),
  fields: prop<Ref<AnyFieldModel>[]>(() => []),
}) {}

@model('SomeField')
class SomeFieldModel extends model({
  id: prop<string>(() => FormUnitIdentityService('somefield'))
}) {}
```

So above, you can see we have three references for every field, when we remove a field we get the following patches:

- one to remove the actual field node from the FormModel
- one to remove the field reference from the PageModel
- one to remove the field reference from the SectionModel
- one to remove the field reference from the SectionRowModel

Now arguably, we could optimise the amount of references we are using yes... but the issue we have is that it's not obvious (to me at least) how I can group these actions that keystone is actually managing for us.

I bring this up, because we implemented the undoMiddleware, wired it up to some undo/redo buttons and was blown away by how little I had to do in order to get a great UX feature... but upon trying to redo, was confused why one click of the redo button didn't bring my field back.

**Comment by xaviergonz** [comment]
Thanks for reporting, could you try v0.48.4? It should be fixed there.

**Comment by sisp** [comment]
Is there any way to group actions more adhoc? Perhaps it's a sign for imperfect state design, but some state changes that I'd like to be grouped in the undo/redo queue don't map to a model method naturally.

**Comment by xaviergonz** [comment]
Now that undoManager has `withGroup`  and `withGroupFlow` I guess this can be closed :)

**Comment by airtonix** [comment]
amazing!
