### ISSUE TITLE
Synchronous Detach? Detaching multiple children in a loop?

### ISSUE THREAD

**Issue by kingpalethe** [xaviergonz/mobx-keystone#167]
Our biggest challenge with Mobx Keystone is finding a reliable way to detach a collection of submodels. For example, given a parent model, we are trying to iterate through child models, calling `detach` on each one, but seem to very often encounter some kind of race condition, where the detaching does not fully complete. Does anyone else have this issue?

**Comment by kingpalethe** [comment]
Is there a reason to use `detach` on each submodel instance individually, instead of just

`ParentModel.submodels = []`

?

**Comment by kingpalethe** [comment]
Here is the reference on `detach`
https://mobx-keystone.js.org/public/api/index.html#detach
It has worked well for us when we have been using it "one at a time" -- like a user clicks something and that thing gets deleted. This always works well.

Using it in a loop, like this:

```
    parent.childThings.forEach((thing) => {
      detach(thing);
    });
```
... seems to result in unpredictable behavior -- like not all the deletions happening, or somehow the javascript execution moving on to the next line before all the detachings are done.

... maybe `detach` is not mean to be used in a loop like this?

**Comment by sisp** [comment]
I haven't looked into the implementation details, but does it work if you loop over the array in reverse order?

**Comment by xaviergonz** [comment]
That's because you are deleting items from an array inside a forEach, which results in an undefined behaviour (for all JS arrays, not just mobx-keystone).

e.g.
```ts
test("x", () => {
  const ar = [0, 1, 2]
  const el: any = []
  ar.forEach((x, i) => {
    el.push([x, i])
    ar.splice(0, 1)
  })
  expect(el.length).toBe(3) // this actuall fails and returns 2
})
```

One way to fix it is to make a copy of the array before using forEach over it, e.g.
```ts
[...arr].forEach(...)
arr.slice().forEach(...)
```

If you just want to detach all items from its parent array and you know the parent array it is usually easier to do one of these though:
```ts
arr.length = 0;
arr = [];
```

detach is usually meant to be used when you want to detach a child from a parent and that parent is unknown. If the parent is known it is usually clearer to just set remove the child from the array/object/field.

**Comment by kingpalethe** [comment]
Thanks!
