### ISSUE TITLE
How to handle Error interface

### ISSUE THREAD

**Issue by crivera** [xaviergonz/mobx-keystone#193]
I have a model class that checks the status on async actions like this:

```
@model("Task")
class Task extends Model({
  id: prop<string>(),
  state: prop<TaskStatus>("pending"),
  error: prop<Error | undefined>(),
}) {

  @modelAction
  update(state: TaskStatus, error?: Error) {
    this.state = state
    this.error = error
  }
}
```

When I pass in an Error from my `modelflow` function I get the following error

```
×
Unhandled Rejection (Error): tweak can only work over models, observable objects/arrays, or primitives, but got Error: Custom Error Message instead
```

in my `modelFlow` I do: `throw new Error("Custom Error Message")` for testing purposes.

Any idea what this means?

**Comment by xaviergonz** [comment]
Is error a model? It is complaining it might be something else. If you need it to be something else and it doesn't need to be serializable then you might just store it as an old fashioned observable property

**Comment by crivera** [comment]
No error is just the JavaScript Error class

**Comment by xaviergonz** [comment]
that's because model properties need to be JSON-serializable (so they can be snapshotted)

Since the Error class is not serializable (is not a model, a primitive value, etc), that's why it complains.

A simple way to fix it is to split the "model mutation" action from the function and moving the error (non serilizable) to a property outside of the model properties

e.g.

```ts
@model("Task")
class Task extends Model({
  id: prop<string>(),
  state: prop<TaskStatus>("pending"),
}) {
  private error?: Error // might be an observable.ref or not

  update(state: TaskStatus, error?: Error) {
    this.updateState(state)
    this.error = error
  }

  @modelAction
  updateState(state: TaskStatus) {
    this.state = state
  }
}
```

Although by doing it that way you loose the ability to include the error in serialized snapshots.

A probably better way to fix that is to create an error model and convert error classes to error models

```ts
@model("Error")
class MError extends Model({
  message: prop<string | undefined>()
}) {}

@model("Task")
class Task extends Model({
  id: prop<string>(),
  state: prop<TaskStatus>("pending"),
  error: prop<MError | undefined>(),
}) {

  @modelAction
  update(state: TaskStatus, error?: Error) {
    this.state = state
    this.error = new MError(error.message) // convert
  }
}
```

**Comment by crivera** [comment]
Awesome thanks
