### ISSUE TITLE
Feature request: Custom ID column

### ISSUE THREAD

**Issue by maccman** [xaviergonz/mobx-keystone#208]
Keystone uses `$modelId` for storing IDs internally.

Pretty much every DB stores IDs as `id` columns.

So you always have to write a mapping layer, e.g.:

```typescript
export function buildModel<T>(model: { new (props: any): T }, props: any): T {
  return new model({
    ...props,
    $modelId: props.$modelId || props.id
  })
}
```

I'm wondering if we can make the name of the ID column settable?

**Comment by xaviergonz** [comment]
Would it be good enough if that id column would auto-populate $modelId on creation but $modelId would still be the source of id information (this is, the id -> $modelId assignation would be done when "new" is used) or would it need to be also the case for "fromSnapshot" (this is, $modelId would stop existing entirely if this other id field would exist) ?

**Comment by maccman** [comment]
I think internally it could work however you'd like (i.e. keep $modelId). As long as their is an `id` getter/setter (and it works in the constructor) should be fine.

**Comment by xaviergonz** [comment]
## 0.50.0

- It is now possible to use a custom property as model id instead of `$modelId` by assigning to a property the new `idProp` value. In any case, model instances can still use `model.$modelId` to read/write this custom property if desired.

## Customizing the ID property

It is possible to use any other custom property as ID source by assigning to it the `idProp` value. For example:

```ts
@model("myApp/ModelWithCustomId")
class ModelWithCustomId extends Model({
  customId: idProp
}) {
  ...
}
```

In this case either `customId` (both in snapshots and instances) or `$modelId` (only in instances) can be used to read / write the ID property.

---

Let me know how it goes

**Comment by maccman** [comment]
Wahoo - will do!

**Comment by maccman** [comment]
Did you say that the class will defer back to $modelID if customId isn't set? I'm trying to load a previously created snapshot (that has $modelId backed into it), it looks like that isn't getting picked up.

<img width="954" alt="Screen Shot 2021-02-15 at 4 43 23 PM" src="https://user-images.githubusercontent.com/2142/107903016-fcb96a80-6fac-11eb-85cf-241bbaf5620d.png">

**Comment by xaviergonz** [comment]
No, what I meant is that this.$modelId will become a getter for the new ID property if set. If you need to transform old models your best bet is the fromSnapshot override in the model class

**Comment by xaviergonz** [comment]
Closing due to lack of feedback, please reopen if needed :)
