### ISSUE TITLE
Computed backrefs without reaction

### ISSUE THREAD

**Issue by sisp** [xaviergonz/mobx-keystone#233]
[Backrefs are currently updated using a `reaction`](https://github.com/xaviergonz/mobx-keystone/blob/0444b0f95bb316d0e3446e2b03d41d6f226ae5e4/packages/lib/src/ref/core.ts#L66-L82) which means a new backref is only available by `getRefsResolvingTo` after the outermost (trans)action has completed. I think it would be better if backrefs did not rely on a `reaction` but instead were computed values.

I think computing backrefs without a `reaction` can be achieved by using an approach similar to root refs based on [`computedWalkTreeAggregate`](https://github.com/xaviergonz/mobx-keystone/blob/0444b0f95bb316d0e3446e2b03d41d6f226ae5e4/packages/lib/src/parent/walkTree.ts#L138-L161). For root refs,  `computedWalkTreeAggregate` walks the tree and creates a reactive computed map of IDs and the corresponding nodes by, so that a root ref can access this map to resolve a reference as long as the node and the ref are part of the same tree. Backrefs could be computed in a similar way, i.e. a map of IDs and and refs that resolve the corresponding nodes could be created. While the map created for root refs contains 1:1 mappings of IDs and nodes, the map needed for backrefs would contain 1:n mappings of IDs and nodes because multiple refs can resolve the same node. Perhaps `computedWalkTreeAggregate` could be generalized so that the map values can be arrays, essentially implementing a "group-by" operation when the predicate returns the same value for multiple nodes.

**Comment by xaviergonz** [comment]
I assume you want to do this to be able to access updated back references from the middle of an action. I'm not sure if cached computeds return a stale value when invoked from actions or not. Btw, would it be OK for your use case to trigger onResolvedValueChanged inside a reaction?

**Comment by sisp** [comment]
Correct. Regarding `onResolvedValueChanged`, ideally no reaction would be used here either, but this is trickier I think (https://github.com/xaviergonz/mobx-keystone/issues/214#issuecomment-792839090, https://github.com/mobxjs/mobx/issues/2795, https://github.com/mobxjs/mobx/pull/2802), but perhaps you have an idea.

**Comment by sisp** [comment]
> I'm not sure if cached computeds return a stale value when invoked from actions or not (would need to test).

This test passes:

```ts
test("cached computed returns an up-to-date value when invoked from an action", () => {
  const a = observable.box(1)
  const b = computed(() => a.get() * 2)

  expect(b.get()).toBe(2)
  
  runInAction(() => {
    a.set(2)
    
    expect(b.get()).toBe(4)
  })
})
```

**Comment by xaviergonz** [comment]
I've been looking into it, but I see no way to do it:
1) your computed walk tree idea 
* cons: not all references are root refs, a custom ref might even link from one root tree to another one if desired
2) keeping all refs in a list so they all can be re-resolved when `getRefsResolvingTo` is called inside an action
 * cons: either causing a memory leak and/or having to dispose them manually
3) tweak the mobx internals (onBecomeStale_) at run-time
* cons: looked promising, but I need to call .get() on the computed before it informs it became stale, and the problem is exactly that I don't know which new references might point to it (not to mention having to use mobx internals in this way is gonna break sooner or later)

The best I can think of is re-resolving references when `getRefsResolvingTo` is called inside an action, but this would only detect dead references, not new ones.

**Comment by xaviergonz** [comment]
Or another option would be to give an optional list of refs to `getRefsResolvingTo` and get those refs re-resolved when inside an action (but then the library user needs to keep his own list of refs)

**Comment by sisp** [comment]
Thank you very much for giving this issue so much thought. I agree with your analysis of the 3 options you described. I think it's a shortcoming of MobX that there is no mechanism for immediately reacting to changes in computed values. But it seems the MobX team does not consider the lack of this feature a problem and declined by PR without much hope for accepting this kind of feature.

Regarding your suggested `forceUpdateBackRefs` function: It feels a bit too much like a workaround in my opinion, especially since this library has such an elegant API.


> 2. keeping all refs in a list so they all can be re-resolved when `getRefsResolvingTo` is called inside an action
> - cons: either causing a memory leak and/or having to dispose them manually

What do you think about using `CustomRef.onAttachedToRootStore` for adding/removing the ref to/from a list of all refs? The way I understand it, every state tree should be registered as a root store anyway. When there are multiple trees, all of them should be registered as root stores. I think you've avoided using the `onAttachedToRootStore` hook internally and preferred `WeakMap`/`WeakSet` for internal book-keeping. If making a state tree a root store is how this library is meant to be used (correct me if I'm wrong), I think it's fine to rely on the `onAttachedToRootStore` hook also internally.

**Comment by xaviergonz** [comment]
> What do you think about using CustomRef.onAttachedToRootStore for adding/removing the ref to/from a list of all refs? The way I understand it, every state tree should be registered as a root store anyway. When there are multiple trees, all of them should be registered as root stores. I think you've avoided using the onAttachedToRootStore hook internally and preferred WeakMap/WeakSet for internal book-keeping. If making a state tree a root store is how this library is meant to be used (correct me if I'm wrong), I think it's fine to rely on the onAttachedToRootStore hook also internally.

I try to avoid it because marking a node as a root store is (in theory) optional, but very practical to be able to get that hook working. That being said, I think that it is better to get it working for those cases (when the ref is part of a root store) than not working at all. The only downside I see though is that calling `getRefsResolvingTo` while inside an action/computed will re-resolve ALL references part of a root store, which depending on the number of refs might be quite a hit so I put this behavior under an option called 'updateAllReferencesIfNeeded'.

@sisp care to check this PR to see if it is good enough?
https://github.com/xaviergonz/mobx-keystone/pull/234

**Comment by sisp** [comment]
Thanks a lot for the PR! I left a couple of comments there.

**Comment by xaviergonz** [comment]
out in 0.57.0

**Comment by sisp** [comment]
Thank you very much!
