### ISSUE TITLE
Transforming snapshots: Replacements for MST snapshotProcessor

### ISSUE THREAD

**Issue by AndrewMorsillo** [xaviergonz/mobx-keystone#285]
I think the following use case is likely fairly common 

- The backend has or expects data in a different format than you can represent it in mobx-keystone. 
- Incoming snapshots need to be transformed from the backend format into your model format
- Outgoing snapshots need to be transformed back into the backend format again. 

So far I don't see any capability to do this in mobx-keystone. I also haven't been able to figure out any clean/simple way to do these transforms outside of mobx-keystone. Snapshots are immutable so it would require something like `JSON.parse(JSON.stringify(snapshot))` to do the transformation outside of keystone on the snapshots before persisting them. Needing to apply transformation to individual fields of a whole snapshot would also likely be error prone and messy, it would be quite easy to forget to transform a field.

MST `types.custom` works well for this. It offers runtime validation and transparent transformation on a prop level. This is really nice because it encapsulates everything about your data transformation in the field definition on the model and is totally reusable.

MST also offers the `snapshotProcessor` for arbitrary transforms on incoming and outgoing snapshots which can be helpful for more complex cases.

IMO these sort of snapshot transformations might be worth supporting in mobx-keystone. There are a couple related issues: https://github.com/xaviergonz/mobx-keystone/issues/275 and https://github.com/xaviergonz/mobx-keystone/issues/121 but I hope this issue can capture the entire scope of the needed functionality from those.

Digging into the code I'm struggling to figure out how this might be implemented. Any pointers or ideas about how this could be achieved would be greatly appreciated!

**Comment by mashaalmemon** [comment]
+1 for a MST like `types.custom` type of implementation. 

Discussion [#292](https://github.com/xaviergonz/mobx-keystone/discussions/292) also touches on a use case for something like this.

I'm imagining how this might be look purely from the viewpoint of a developer using the library. I'm also taking inspiration from the existing framework naming etc. Keeping with the theme of typescript and classes I can imagining some kind of implementation like so:
* a `customProp` function (instead of `prop` or `idProp`)
* The `customProp` would, as a generic take a class implementation of a subclass of BaseCustomProp (developer would extend BaseCustomProp to make the custom type)
   * The `BaseCustomProp` class would have all the basic methods needed like in `types.custom`, with abstract methods like `fromSnapshot`, `toSnapshot` that need to be implemented by the developer who creates the custom type.
   * The `BaseCustomProp` class would itself be a generic with `ImmutableType` and `InputType` specified, and `fromSnapshot` and `toSnapshot` would use them appropriately.

In terms of integration into the framework, I don't know enough about the library to know where in code the `fromSnapshot` and `toSnapshot` methods of the custom type would be called. @xaviergonz, any ideas?

**Comment by xaviergonz** [comment]
I'm working on an implementation that'd work like this:

```ts
const _timestampToDateTransform: ModelPropTransform<number, Date> = {
  transform({ originalValue, cachedTransformedValue }) {
    return cachedTransformedValue ?? new Date(originalValue)
  },

  untransform({ transformedValue, cacheTransformedValue }) {
    cacheTransformedValue()
    return +transformedValue
  },
}

export const timestampToDateTransform = () => _timestampToDateTransform

  class T extends Model({
    date: prop<number>().withSetter().withTransform(timestampToDateTransform()),
  }) {
  }

  const t = new T({
    date: new Date(1000),
  })

  assert(t.date, _ as Date)
  expect(t.date instanceof Date).toBe(true)
  expect(+t.date).toBe(1000)

  assert(t.$.date, _ as number)
  expect(t.$.date).toBe(1000)

  t.setDate(new Date(2000))
```

**Comment by xaviergonz** [comment]
New property transforms + context apply/applyComputed were released as part of v0.61.0

Docs:
- https://mobx-keystone.js.org/mapsSetsDates 
- https://mobx-keystone.js.org/contexts

Let me know if that solves your case completely/partially

**Comment by AndrewMorsillo** [comment]
@xaviergonz Thanks for implementing this, it's greatly appreciated! I think the transforms could be useful but they don't quite solve the cases in this issue.

There's still the case where a backend/API _requires_ a snapshot to be in a different format than is output by mobx-keystone in order to persist it. In your example `getSnapshot(t)` is returning the field `date` as a `number`. This makes the snapshot JSON compatible but there's no easy way to transform it for persistence. 

I think it would be useful to have a way to arbitrarily transform snapshot output both at a per-field level and at a top level like MST's `snapshotProcessor`. 

Data written to a backend could be consumed by many other systems or in non-greenfield projects be in a format constrained by those other systems such that we're not free to alter the structure to match the way we would like to model it in mobx-keystone. Allowing snapshot types to differ from the actual model types would solve this issue.

**Comment by xaviergonz** [comment]
I'll give it a thought. Note that no matter what fromSnapshot will need to take a snapshot (JSON) as input and toSnapshot will need to generate a snapshot (JSON) as output, since there's no other way to support JSON patches, etc otherwise.

**Comment by justin-hackin** [comment]
@AndrewMorsillo thanks for raising this, I am facing an issue that relates to this and I am also wishing for this library to:

> allow SnapshotInOf<ModelType> and SnapshotOutOf<ModelType> to have arbitrarily different shapes than ModelType along with a way to specify the transformations to/from snapshot those snapshot types on the model

My use case is this: I'm using the new context apply feature to create prop factories that 1) annotate properties in my keystone tree with metadata 2) encapsulate functionality (getters/actions) based upon the metadata.  Now I can very succinctly define a data structure and automatically generate all the inputs needed to modify the properties with this metadata. It removes a lot of the hassle of wiring Material UI components up to my data model.  However, this solution is not at all compatible with restoring snapshots.

 I am forced to make the metadata container models keystone Models which gives them an $modelId when they don't really need it. For each metadata-annotated property, the snapshot $modelId is different than the generated $modelId.  This means that when applying the snapshot the original node gets detached an a new one created, but that new model doesn't have the context data on it.  

What I would prefer to do is make the $modelId be equal to a string representation of the Path from the root store but that requires the node being already attached to the root store leading to a "chicken and egg" kind of problem.  With a custom fromSnapshot/toSnapshot I could at least ignore the $modelId in the applied snapshot to prevent the nodes from being disposed and re-initialized or just re-apply the context to the newly created node.

That would not require changing the shape of the data. However, since the metadata container nodes only have a single property `value` it would also be useful to be able to change the shape of the snapshot in order to flatten the `value` props.

**Comment by xaviergonz** [comment]
would this suffice as a replacement for snapshot processors?

https://github.com/xaviergonz/mobx-keystone/pull/326

**Comment by xaviergonz** [comment]
Besides the model one above, just added in v0.64.0 `withSnapshotProcessor` for model single props

**Comment by xaviergonz** [comment]
Closing due to lack of feedback on the released features that should address this
