### ISSUE TITLE
How to properly type model creation data?

### ISSUE THREAD

**Issue by terrysahaidak** [xaviergonz/mobx-keystone#41]
UPDATE: For everyone looking for a specific type of model creation data – use `ModelCreationData<T>`

I'm still figuring out how to properly do some things in TS, so I'm stuck typing the server response which I'm going to pass as the model data. Just something like `SnapshotIn<typeof TodoModel>` in MST. `SnapshotInOf` from `mobx-keystone` isn't the right thing since it requires the `modelTypeKey` to be in the object itself, here is example:

```ts
@model('Todo')
export class TodoModel extends Model({
  id: prop<string>(() => uuid()),
  text: prop<string>(),
  completed: prop<boolean>(false),
}) {

}

// this throws an error the modelTypeKey is missing
const snapshot: SnapshotInOf<TodoModel> = {
  text: 'test',
}

const m = new TodoModel(snapshot);
```

**Comment by xaviergonz** [comment]
That's because `$modelType` is actually required to be in model snapshots before `fromSnapshot` can be used on them (or else you will get a plain object and not a model instance).

There are several ways around this:

1) Inject the model type in the snapshot (you also need to inject it for any submodels you may have)

```ts
const backendData = ...
const snapshot =  {
  ...modelSnapshotInWithMetadata(TodoModel, backendData),
  // if there are submodels
  submodel1: modelSnapshotInWithMetadata(SubModel, backendData.submodel1)
}
const todo = fromSnapshot<TodoModel>(snapshot)
```

2) Create a todo instance (again, you might have to call new Model for sub-models)

```ts
const backendData = ...
const todo = new TodoModel({
  ...backendData,
  // if there are submodels
  submodel1: new Submodel(backendData.submodel1),
})
```

3) Actually make the backend inject the "$modelType" in returned data models (the easiest one if it is possible)

I was thinking of adding a registrable callback so whenever fromSnapshot finds an object without `$modelType` will be called with the object and can return the model class it should be, but that'd mean you'd need to somehow be able to infer it from the structure...

Something like:

```ts
const disposer = registerModelResolver((obj: any) => {
  if (somehowIknowThatObjStructureIsLikeFooModel) {
    return FooModel
  }
  else {
    return undefined
  }
})
```

The only way (AFAIK) to avoid that would be to force the whole type system to be runtime type checked, and use this type check info to infer the model type (which is what mobx-state-tree does).

**Comment by xaviergonz** [comment]
Another option would be to have an optional `resolvePathType` method on models, so you would be able to use the path instead of the object structure.

```ts
@model(...)
class FooRootModel extends Model(...) {
  resolvePathType(path, subObj) {
    if (path.is(["a", "b"]) return FooSubModel1
    // if FooSubModel1 has unknown submodels it will try to use its `resolvePathType` to figure them out
    
    if (path.is(["a", "objMap", any]) return FooSubModel2
    if (path.is(["a", "whatever", (k) => k.startsWith("bleh"), "something"]) return FooSubModel3
    return undefined
  }
}

const m = fromSnapshot(FooRootModel, backendData)
```

with probably a default implementation where if it is declared with "tcProp" it will try to use that first to figure out the model type

Maybe that's more useful?

**Comment by terrysahaidak** [comment]
Don't you find that as just a really simply and common case which requires a lot of extra steps just like I do?

I think there should be some kind of type which just allows you to pass some JSON into the model constructor, just like that:

```ts
// this is just a pseudocode
const json: TodoModel.Data = {
  text: 'test',
}

const m = new TodoModel(json);
```

Even without submodules or so. My point here is that I'm just want to create a new instance. Want to use not the exact snapshot, but something I would just write in the object that constructor accepts. Maybe I'm not familiar with TypeScript enough so I'm seeing it different, just from my perspective, but please let me know where I'm wrong.

**Comment by xaviergonz** [comment]
If the model doesn't have sub-models then it should work.
e..g
```ts
@model("asd")
class MM extends Model({text: prop<string>()}) {}

const data = {text: "hi"}
const mm = new MM(data)

const data2: ModelCreationData<MM> = {text: "hi"}
const mm2 = new MM(data)
```

(reminds me I should make `ModelCreationData` public I guess :) )

**Comment by xaviergonz** [comment]
Nevermind, `ModelData<M>` and `ModelCreationData<M>` are public, I just never wrote about them in the docs

**Comment by terrysahaidak** [comment]
`ModelCreationData` – is the exact type I wanted, thank you. 

Is the `MM.Data` as a replacement of `ModelCreationData<MM>` make any sense for you? Not sure if it's even possible or has some perf impact.

**Comment by xaviergonz** [comment]
You would need to write `typeof MM.CreationData` then. I've always found that people get confused on why it doesn't work when they don't write `typeof`.

**Comment by terrysahaidak** [comment]
Got it, so ok, when it looks fine.

For some reason, `ModelCreationData` didn't work for me when I've tried it (just been guessing by its name), but seems like a problem with VSCode, sometimes it just lags.

Seems like my question is answered and that issue is resolved, thank you!

Should I keep it open until you add some docs for ModelCreationData type?

**Comment by xaviergonz** [comment]
Just wrote them :) But I think it is nice to keep this one open in case somebody else has the same issue.

**Comment by xaviergonz** [comment]
Closing, I think this issue has been open long enough :)
