### ISSUE TITLE
Model types in properties

### ISSUE THREAD

**Issue by RWOverdijk** [xaviergonz/mobx-keystone#61]
I was just pointed in the direction of this project because I mentioned wanting to build something similar myself. I took a quick look, read some docs and want to say you (singular? Plural?) did a good job!

For now I only have two questions:

- Are you on slack/gitter somewhere?
- Why aren't types specified as properties, with decorators instead of a function to extend from?

Thanks for building this, I'm looking forward to working with it.

**Comment by xaviergonz** [comment]
Hey, thanks!

There's currently no channel for the project, but feel free to post here or in a new issue if you have doubts after reading the docs. 

As for why not going the decorator route is basically because of typings, being able to  separate data (that should be in a snapshot) from views for example (that should not be in a snapshot yet are also declared as a property) or volatile data among other reasons. If decorators supported changing the target type in TS they could have been used, but they can't.

**Comment by RWOverdijk** [comment]
@xaviergonz I hope you don't think I'm being a smart ass by saying this but if a decorator decorates a property as a type (serializable) that could still work. It's what I do with Wetland ORM. It also makes it easy to proxy the right properties that way.

Regarding typing that's true, you'll need double typings or interfaces. There's just something appealing about making it look like this:

```ts
class Foo {
  @prop public name: string;

  @tProp(types.array(types.model<Todo>(Todo)), () => [])
  private todos: Todo[];
}
```

Holding on to wetland, It's what I do there as well. I set the type for the mapping and the type for typescript. It's less magic, true, but also more predictable. But that's not a big deal, I could write a lib around it for myself. 😄
